-- Run this once in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'student' check (role in ('student', 'teacher', 'admin')),
  student_id text,
  section text,
  program text,
  year_level text,
  enrollment_status text not null default 'active' check (enrollment_status in ('active', 'dropped_out')),
  phone text,
  guardian_name text,
  guardian_phone text,
  address text,
  created_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  teacher_id uuid references public.profiles(id) on delete set null,
  term text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.grades (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  grade numeric(5,2) not null check (grade between 0 and 100),
  gpa numeric(4,2),
  attendance numeric(5,2) check (attendance between 0 and 100),
  remarks text,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  unique(student_id, subject_id)
);

create table if not exists public.enrollments (
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  enrollment_status text not null default 'active' check (enrollment_status in ('active', 'dropped_out')),
  enrolled_at timestamptz not null default now(),
  primary key (student_id, subject_id)
);

create table if not exists public.teacher_allowlist (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.account_allowlist (
  email text primary key,
  role text not null check (role in ('student', 'teacher', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.account_allowlist drop constraint if exists account_allowlist_role_check;
alter table public.account_allowlist add constraint account_allowlist_role_check check (role in ('student', 'teacher', 'admin'));

alter table public.profiles add column if not exists section text;
alter table public.profiles add column if not exists enrollment_status text not null default 'active';
alter table public.enrollments add column if not exists enrollment_status text not null default 'active';
do $$
begin
  alter table public.profiles add constraint profiles_enrollment_status_check check (enrollment_status in ('active', 'dropped_out'));
exception
  when duplicate_object then null;
end $$;
do $$
begin
  alter table public.enrollments add constraint enrollments_status_check check (enrollment_status in ('active', 'dropped_out'));
exception
  when duplicate_object then null;
end $$;
alter table public.grades add column if not exists published boolean not null default false;

alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.grades enable row level security;
alter table public.enrollments enable row level security;
alter table public.teacher_allowlist enable row level security;
alter table public.account_allowlist enable row level security;

create or replace function public.is_teacher()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'teacher');
$$;

create or replace function public.is_subject_teacher(requested_subject_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.subjects
    where id = requested_subject_id and teacher_id = auth.uid()
  ) or exists (
    select 1
    from public.subjects s
    join public.profiles p on p.id = auth.uid()
    where s.id = requested_subject_id
      and s.code = 'ECC12'
      and p.role = 'teacher'
      and p.full_name = 'Mr. Vanie Santos'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    coalesce(
      (select role from public.account_allowlist where lower(email) = lower(new.email) limit 1),
      case when exists (
        select 1 from public.teacher_allowlist
        where lower(email) = lower(new.email)
      ) then 'teacher' else 'student' end
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

drop policy if exists "Users can view their own profile" on public.profiles;
drop policy if exists "Users can create their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;
drop policy if exists "Teachers can view student profiles" on public.profiles;
drop policy if exists "Teachers can update student profiles" on public.profiles;
drop policy if exists "Signed in users can view subjects" on public.subjects;
drop policy if exists "Students can view their own grades" on public.grades;
drop policy if exists "Teachers can manage grades" on public.grades;
drop policy if exists "Students can view their enrollments" on public.enrollments;
drop policy if exists "Teachers can view subject enrollments" on public.enrollments;
drop policy if exists "Teachers can update subject enrollments" on public.enrollments;
drop policy if exists "Teachers can manage subject enrollments" on public.enrollments;
drop policy if exists "Teachers can manage assigned grades" on public.grades;

create policy "Users can view their own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can create their own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id);
create policy "Teachers can view student profiles" on public.profiles for select using (auth.uid() = id or public.is_teacher());
create policy "Teachers can update student profiles" on public.profiles for update using (public.is_teacher());
create policy "Signed in users can view subjects" on public.subjects for select to authenticated using (true);
create policy "Students can view their own grades" on public.grades for select using (auth.uid() = student_id and published = true);
create policy "Students can view their enrollments" on public.enrollments for select using (auth.uid() = student_id);
create policy "Teachers can view subject enrollments" on public.enrollments for select using (public.is_subject_teacher(subject_id));
create policy "Teachers can manage subject enrollments" on public.enrollments for all
using (public.is_subject_teacher(subject_id))
with check (
  public.is_subject_teacher(subject_id)
  and exists (select 1 from public.profiles where id = enrollments.student_id and role = 'student')
);
create policy "Teachers can manage assigned grades" on public.grades for all
using (
  public.is_subject_teacher(subject_id)
  and exists (select 1 from public.enrollments where student_id = grades.student_id and subject_id = grades.subject_id)
)
with check (
  public.is_subject_teacher(subject_id)
  and exists (select 1 from public.enrollments where student_id = grades.student_id and subject_id = grades.subject_id)
);

insert into public.subjects (code, name, term)
values ('ECC12', 'Business Law & Taxation', 'Term 2')
on conflict (code) do nothing;

insert into public.subjects (code, name, term)
values
  ('PM101', 'Project Management', 'Term 2'),
  ('RM110', 'Research Methods', 'Term 2')
on conflict (code) do nothing;

-- Approved teacher accounts. agentblacks17@gmail.com is Mr. Vanie Santos for ECC12.
delete from public.account_allowlist
where lower(email) in ('santos@gmail.com', 'van@gmail.com', 'agentblacks17@gmail.com');

insert into public.account_allowlist (email, role)
values
  ('santos@gmail.com', 'teacher'),
  ('van@gmail.com', 'teacher'),
  ('agentblacks17@gmail.com', 'teacher'),
  ('student01@example.com', 'student'),
  ('student02@example.com', 'student'),
  ('student03@example.com', 'student'),
  ('student04@example.com', 'student'),
  ('student05@example.com', 'student'),
  ('student06@example.com', 'student'),
  ('student07@example.com', 'student'),
  ('student08@example.com', 'student'),
  ('student09@example.com', 'student'),
  ('student10@example.com', 'student')
on conflict (email) do update set role = excluded.role;

update public.profiles
set role = 'teacher', full_name = 'Mr. Vanie Santos'
where id in (
  select id from auth.users
  where lower(email) = lower('agentblacks17@gmail.com')
);

update public.profiles
set role = 'teacher', full_name = 'Ms. Mia Santos'
where id in (
  select id from auth.users
  where lower(email) = lower('santos@gmail.com')
);

-- Apply allowlist roles to accounts that already exist.
update public.profiles p
set role = a.role
from public.account_allowlist a
join auth.users u on lower(u.email) = lower(a.email)
where p.id = u.id;

-- Assign each unit to its teacher after the accounts exist.
update public.subjects
set teacher_id = (select id from auth.users where lower(email) = lower('agentblacks17@gmail.com'))
where code = 'ECC12'
  and exists (select 1 from auth.users where lower(email) = lower('agentblacks17@gmail.com'));

update public.subjects
set teacher_id = (select id from auth.users where lower(email) = lower('van@gmail.com'))
where code = 'PM101'
  and exists (select 1 from auth.users where lower(email) = lower('van@gmail.com'));

update public.subjects
set teacher_id = null
where code = 'RM110';

update public.subjects
set teacher_id = (select id from auth.users where lower(email) = lower('santos@gmail.com'))
where code = 'RM110'
  and exists (select 1 from auth.users where lower(email) = lower('santos@gmail.com'));

update public.profiles
set full_name = 'Mr. Vanie Santos'
where id in (
  select id from auth.users
  where lower(email) = lower('agentblacks17@gmail.com')
);

update public.profiles
set full_name = 'Raqueim Carlos'
where id = (select id from auth.users where lower(email) = lower('van@gmail.com'));

update public.profiles
set full_name = 'Jovanie Santos', section = '4-9'
where id = (select id from auth.users where lower(email) = lower('jovanierams@gmail.com'));

insert into public.enrollments (student_id, subject_id)
select u.id, s.id
from auth.users u
cross join public.subjects s
where lower(u.email) = lower('jovanierams@gmail.com')
  and s.code in ('ECC12', 'PM101', 'RM110')
on conflict do nothing;

-- Demo student profiles and enrollments. Create these emails in Supabase Auth first.
update public.profiles p
set full_name = demo.full_name, student_id = demo.student_id, section = demo.section
from (values
  ('student01@example.com', 'Demo Student 01', 'DEMO-0001', '4-1'),
  ('student02@example.com', 'Demo Student 02', 'DEMO-0002', '4-1'),
  ('student03@example.com', 'Demo Student 03', 'DEMO-0003', '4-2'),
  ('student04@example.com', 'Demo Student 04', 'DEMO-0004', '4-2'),
  ('student05@example.com', 'Demo Student 05', 'DEMO-0005', '4-3'),
  ('student06@example.com', 'Demo Student 06', 'DEMO-0006', '4-3'),
  ('student07@example.com', 'Demo Student 07', 'DEMO-0007', '4-4'),
  ('student08@example.com', 'Demo Student 08', 'DEMO-0008', '4-4'),
  ('student09@example.com', 'Demo Student 09', 'DEMO-0009', '4-5'),
  ('student10@example.com', 'Demo Student 10', 'DEMO-0010', '4-5')
) as demo(email, full_name, student_id, section)
join auth.users u on lower(u.email) = lower(demo.email)
where p.id = u.id;

insert into public.enrollments (student_id, subject_id)
select u.id, s.id
from auth.users u
cross join public.subjects s
where lower(u.email) in (
  'student01@example.com', 'student02@example.com', 'student03@example.com',
  'student04@example.com', 'student05@example.com', 'student06@example.com',
  'student07@example.com', 'student08@example.com', 'student09@example.com',
  'student10@example.com'
)
and s.code in ('ECC12', 'PM101', 'RM110')
on conflict do nothing;