-- Run this once in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'student' check (role in ('student', 'teacher', 'admin')),
  student_id text,
  section text,
  program text,
  year_level text,
  phone text,
  guardian_name text,
  guardian_phone text,
  address text,
  created_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  teacher_id uuid references public.profiles(id) on delete set null,
  term text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.grades (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  grade numeric(5,2) not null check (grade between 0 and 100),
  gpa numeric(4,2),
  attendance numeric(5,2) check (attendance between 0 and 100),
  remarks text,
  created_at timestamptz not null default now(),
  unique(student_id, subject_id)
);

create table if not exists public.enrollments (
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  enrolled_at timestamptz not null default now(),
  primary key (student_id, subject_id)
);

create table if not exists public.teacher_allowlist (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.account_allowlist (
  email text primary key,
  role text not null check (role in ('student', 'teacher')),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists section text;

alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.grades enable row level security;
alter table public.enrollments enable row level security;
alter table public.teacher_allowlist enable row level security;
alter table public.account_allowlist enable row level security;

create or replace function public.is_teacher()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'teacher');
$$;

create or replace function public.is_subject_teacher(requested_subject_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.subjects
    where id = requested_subject_id and teacher_id = auth.uid()
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    coalesce(
      (select role from public.account_allowlist where lower(email) = lower(new.email) limit 1),
      case when exists (
        select 1 from public.teacher_allowlist
        where lower(email) = lower(new.email)
      ) then 'teacher' else 'student' end
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

drop policy if exists "Users can view their own profile" on public.profiles;
drop policy if exists "Users can create their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;
drop policy if exists "Teachers can view student profiles" on public.profiles;
drop policy if exists "Signed in users can view subjects" on public.subjects;
drop policy if exists "Students can view their own grades" on public.grades;
drop policy if exists "Teachers can manage grades" on public.grades;
drop policy if exists "Students can view their enrollments" on public.enrollments;
drop policy if exists "Teachers can view subject enrollments" on public.enrollments;
drop policy if exists "Teachers can manage assigned grades" on public.grades;

create policy "Users can view their own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can create their own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id);
create policy "Teachers can view student profiles" on public.profiles for select using (auth.uid() = id or public.is_teacher());
create policy "Signed in users can view subjects" on public.subjects for select to authenticated using (true);
create policy "Students can view their own grades" on public.grades for select using (auth.uid() = student_id);
create policy "Students can view their enrollments" on public.enrollments for select using (auth.uid() = student_id);
create policy "Teachers can view subject enrollments" on public.enrollments for select using (public.is_subject_teacher(subject_id));
create policy "Teachers can manage assigned grades" on public.grades for all
using (
  public.is_subject_teacher(subject_id)
  and exists (select 1 from public.enrollments where student_id = grades.student_id and subject_id = grades.subject_id)
)
with check (
  public.is_subject_teacher(subject_id)
  and exists (select 1 from public.enrollments where student_id = grades.student_id and subject_id = grades.subject_id)
);

insert into public.subjects (code, name, term)
values ('ECC12', 'Business Law & Taxation', 'Term 2')
on conflict (code) do nothing;

insert into public.subjects (code, name, term)
values
  ('PM101', 'Project Management', 'Term 2'),
  ('RM110', 'Research Methods', 'Term 2')
on conflict (code) do nothing;

-- Approved teacher accounts.
insert into public.account_allowlist (email, role)
values
  ('santos@gmail.com', 'teacher'),
  ('van@gmail.com', 'teacher'),
  ('agentblacks17@gmail.com', 'teacher')
on conflict (email) do update set role = excluded.role;

-- Apply allowlist roles to accounts that already exist.
update public.profiles p
set role = a.role
from public.account_allowlist a
join auth.users u on lower(u.email) = lower(a.email)
where p.id = u.id;

-- Assign ECC12 to the teacher after that account exists:
update public.subjects
set teacher_id = (select id from auth.users where lower(email) = lower('agentblacks17@gmail.com'))
where code = 'ECC12'
  and exists (select 1 from auth.users where lower(email) = lower('agentblacks17@gmail.com'));

update public.profiles
set full_name = 'Mr. Vanie Santos'
where id = (select id from auth.users where lower(email) = lower('agentblacks17@gmail.com'));

update public.profiles
set full_name = 'Raqueim Carlos'
where id = (select id from auth.users where lower(email) = lower('van@gmail.com'));

update public.profiles
set full_name = 'Ms. Mia Santos'
where id = (select id from auth.users where lower(email) = lower('santos@gmail.com'));

update public.profiles
set full_name = 'Jovanie Santos', section = '4-9'
where id = (select id from auth.users where lower(email) = lower('jovanierams@gmail.com'));

update public.subjects
set teacher_id = (select id from auth.users where lower(email) = lower('van@gmail.com'))
where code = 'PM101'
  and exists (select 1 from auth.users where lower(email) = lower('van@gmail.com'));

update public.subjects
set teacher_id = (select id from auth.users where lower(email) = lower('santos@gmail.com'))
where code = 'RM110'
  and exists (select 1 from auth.users where lower(email) = lower('santos@gmail.com'));

insert into public.enrollments (student_id, subject_id)
select u.id, s.id
from auth.users u
cross join public.subjects s
where lower(u.email) = lower('jovanierams@gmail.com')
  and s.code in ('ECC12', 'PM101', 'RM110')
on conflict do nothing;